const drawC = document.getElementById('bezier'),
      drawC01 = document.getElementById('bezier01'),
      drawC02 = document.getElementById('bezier02'),
      drawC03 = document.getElementById('bezier03'),
      drawC04 = document.getElementById('bezier04');
const ctx = drawC.getContext('2d'),
      ctx01 = drawC01.getContext('2d'),
      ctx02 = drawC02.getContext('2d'),
      ctx03 = drawC03.getContext('2d'),
      ctx04 = drawC04.getContext('2d');